<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24" started-at="2019-03-18T15:11:11Z" finished-at="2019-03-18T15:11:11Z">
    <groups>
      <group name="smoke">
        <method signature="test_ng_01.test_01()[pri:0, instance:Se_2019.test_ng_01@58651fd0]" name="test_01" class="Se_2019.test_ng_01"/>
        <method signature="test_ng_01.test_02()[pri:0, instance:Se_2019.test_ng_01@58651fd0]" name="test_02" class="Se_2019.test_ng_01"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Test" duration-ms="24" started-at="2019-03-18T15:11:11Z" finished-at="2019-03-18T15:11:11Z">
      <class name="Se_2019.test_ng_01">
        <test-method status="FAIL" signature="test_01()[pri:0, instance:Se_2019.test_ng_01@58651fd0]" name="test_01" duration-ms="9" started-at="2019-03-18T23:11:11Z" finished-at="2019-03-18T23:11:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Se_2019.test_ng_01.test_01(test_ng_01.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_01 -->
        <test-method status="PASS" signature="test_02()[pri:0, instance:Se_2019.test_ng_01@58651fd0]" name="test_02" duration-ms="1" started-at="2019-03-18T23:11:11Z" finished-at="2019-03-18T23:11:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_02 -->
      </class> <!-- Se_2019.test_ng_01 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
